version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravelApp
    restart: unless-stopped
    volumes:
      - .:/var/www/html:cached
    environment:
      - APP_ENV=local
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=true
      - DB_CONNECTION=mariadb
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=mere
      - DB_USERNAME=mere
      - DB_PASSWORD=123+aze
    depends_on:
      - db

  web:
    image: nginx:latest
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8005:80"
    volumes:
      - .:/var/www/html:cached
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mariadb:latest
    container_name: larave_ldb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mere
      MYSQL_USER: mere
      MYSQL_PASSWORD: 123+aze
    ports:
      - "30120:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: laravel_phpmyadm
    restart: unless-stopped
    ports:
      - "8883:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - db

volumes:
  db_data: